// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono4
//    output | qmk_userspace
//    input  | nostromo-greeble.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_nostromo_greeble_length;
extern const uint8_t  gfx_nostromo_greeble[183];
